# Uncomment the next line to define a global platform for your project
platform :ios, '16.6'

target 'CoffeeMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeeMap
  pod 'Alamofire'
  pod 'Swinject'

  target 'CoffeeMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeMapUITests' do
    # Pods for testing
  end

end
